drop table HomeList;
drop table Categorie; 
drop table addInfo;
drop table addContent;
drop table userInfo;
select * from HomeList;
select * from Categorie;
select * from addInfo;
select * from addContent;
select * from userInfo;